- name: Custom
  hosts: moomin_hosts

  tasks:
  - name: Update all packages on the systems
    yum:
        name: '*'
        state: latest

  - name: Add epel-release repo
    yum: 
        name: epel-release
        state: present 

  - name: Install NTP, ngnix, MySQL
    yum:
        name: 
          - ntp
          - nginx
          - mysql-server
          - python3
          - python-pip
          - python2-PyMySQL
        state: present
  
  - name: Install PyMySql
    pip:
        name: PyMySql
        state: present
        executable: pip3

  - name: Replaces NTP default config
    copy:
        src: ntp.conf
        dest: /etc/ntp.conf
        force: yes

  - name: Start NTP
    service:
        name: ntpd
        state: started

  - name: Start nginx
    service:
        name: nginx
        state: started      

  - name: Start mysql
    service:
        name: mysqld
        state: started

  - name: Create user in MySQL
    mysql_user:
        name: moomin
        priv: '*.*:ALL'
        state: present

  - name: Create database in MySQL
    mysql_db:
        name: moomin_db
        state: present   
