- name: Set SSH environment 
  hosts: moomin_hosts

  tasks:
    - name: Create ~/.ssh dir
      file:
          path: /home/moomin/.ssh
          state: directory
   
    - name: Create `authorized_keys` if absent
      file:
          path: /home/moomin/.ssh/authorized_keys
          state: touch

- name: Set SSH keys to host-1
  hosts: host-1
  
  tasks:
    - name: Copy ssh private key to host-1
      copy:
          src: host-1_rsa
          dest: /home/moomin/.ssh/id_rsa
          owner: moomin
          group: moomin
          mode: 0600

- name: Copy SSH key to host-2
  hosts: host-2
  
  tasks:
    - name: Copy ssh private key to host-2
      copy:
          src: host-2_rsa
          dest: /home/moomin/.ssh/id_rsa
          owner: moomin
          group: moomin
          mode: 0600
  
- name: Copy SSH key to host-3
  hosts: host-3
  
  tasks:
    - name: Copy ssh private key to host-3
      copy:
          src: host-3_rsa
          dest: /home/moomin/.ssh/id_rsa
          owner: moomin
          group: moomin
          mode: 0600   
        
- name: Put PubKeys to hosts
  hosts: moomin_hosts
  tasks:
    - name: add PubKey of host-1
      lineinfile:
          path: /home/moomin/.ssh/authorized_keys
          line: "{{ pubkey1 }}"
          state: present

    - name: add PubKey of host-2
      lineinfile:
          path: /home/moomin/.ssh/authorized_keys
          line: "{{ pubkey2 }}"
          state: present

    - name: add PubKey of host-3
      lineinfile:
          path: /home/moomin/.ssh/authorized_keys
          line: "{{ pubkey3 }}"
          state: present

    - name: Set access privileges to authorezued_keys
      file:
          path: /home/moomin/.ssh/authorized_keys
          owner: moomin
          group: moomin
          mode: 0644
    
    - name: Set access privileges to .ssh/
      file:
          path: /home/moomin/.ssh
          owner: moomin
          group: moomin
          mode: 0744

- name: Set sudo for moomin user
  hosts: moomin_hosts
  
  tasks:
    - name: Add moomin group to sudoers
      lineinfile:
          path: /etc/sudoers
          line: "moomin ALL=(ALL) NOPASSWD:ALL"
          state: present



