# tasks file for roles/user

- name: Create new user
  user:
    name: "{{ user_name }}"
    state: present
  notify:
        - Add new user to sudoers

- name: Create .ssh/
  file:
    name: "/home/{{ user_name }}/.ssh"
    state: directory

- name: Copy private keys
  copy:
    src: "{{ private_key }}"
    dest: "/home/{{ user_name }}/.ssh/id_rsa"
    decrypt: yes

- name: Add authorized keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', 'files/'+ item + '_rsa.pub') }}"
  with_items: "{{ ansible_play_batch }}"
