# tasks file for roles/nginx

- name: Install nginx
  yum:
    name: nginx
    state: present
  notify:
    - Put nginx.conf
    - Enable nginx

- name: Start nginx
  service:
    name: nginx
    state: started 

- name: Setup web-site
  include_tasks: setup-web.yml

- name: Add http port to firewall rules
  firewalld:
     port: "{{ port_num }}/tcp"
     permanent: yes
     state: enabled  

- name: Change SELinux context 
  command: "chcon -Rv system_u:object_r:httpd_sys_content_t:s0 /web"
