# tasks file for roles/nginx

- name: Install nginx
  yum:
    name: nginx
    state: present
  notify:
    - Enable nginx

- name: Put nginx.conf
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted 

- name: Setup web-site
  include_tasks: setup-web.yml

- name: Add http port to firewall rules
  firewalld:
     port: "{{ port_num }}/tcp"
     permanent: true
     state: enabled  
  notify:
     - Restart firewalld

- name: Change SELinux context 
  command: "chcon -Rv system_u:object_r:httpd_sys_content_t:s0 /web"
